# Generated by Django 2.1.3 on 2018-12-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('ooo', 'ООО'), ('oao', 'ОАО'), ('pao', 'ПАО'), ('zao', 'ЗАО'), ('ao', 'АО')], max_length=16, verbose_name='Форма')),
                ('name', models.CharField(max_length=128, verbose_name='Название организации')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('basic_survey', models.BooleanField(default=False, verbose_name='Базовый опрос пройден')),
                ('governmental', models.BooleanField(verbose_name='Тип')),
                ('subtype', models.CharField(choices=[('force', 'Силовики'), ('gov_comp', 'Гос. компания'), ('gov_inst', 'Гос. учреждение'), ('gen_podr', 'Ген. подрядчик'), ('pr_comp', 'Частная компания'), ('smb', 'SMB')], max_length=64, verbose_name='Подтип')),
                ('sanctions', models.BooleanField(default=False, verbose_name='Санкции')),
                ('crimea', models.BooleanField(default=False, verbose_name='Крым')),
                ('imp', models.BooleanField(default=False, verbose_name='Импортозамещение')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=64, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=14, verbose_name='Телефон')),
                ('phone_number2', models.CharField(blank=True, max_length=14, verbose_name='Доп. телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64)),
                ('model_row', models.CharField(max_length=64)),
                ('vendor1', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('SKU', models.CharField(max_length=64)),
                ('vendor2', models.CharField(max_length=64)),
                ('model2', models.CharField(max_length=64)),
                ('SKU2', models.CharField(max_length=64)),
                ('imp', models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], max_length=8, verbose_name='Импортозамещение')),
                ('ST1', models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], max_length=8, verbose_name='СТ1 ГОС образца')),
                ('torp', models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], max_length=8, verbose_name='Сертификат ТОРП')),
                ('eac', models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], max_length=8, verbose_name='EAC')),
                ('sanctions', models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], max_length=8, verbose_name='Санкции')),
                ('crimea', models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], max_length=8, verbose_name='Крым')),
                ('price_bracket', models.CharField(choices=[('prem', 'Premium'), ('avrg', 'Средняя цен. кат.'), ('noname', 'No name')], max_length=64, verbose_name='Бюджет')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Название заказа')),
                ('status', models.CharField(choices=[('query', 'Запрос'), ('lead', 'Лид'), ('order', 'Заявка'), ('declined', 'Отказ'), ('successful', 'Успешно реализован')], max_length=64, verbose_name='Статус')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('decline_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('comments', models.TextField(verbose_name='Примечания к заказу')),
                ('survey', models.BooleanField(default=False, verbose_name='Опрос пройден')),
                ('product_type', models.CharField(choices=[('server', 'Сервера'), ('shd', 'СХД')], max_length=64, verbose_name='Направление')),
                ('upgrade', models.BooleanField(verbose_name='Апгрейд')),
                ('fav_brands', models.CharField(choices=[('noname', 'No name'), ('avrg', 'Средняя цена'), ('premium', 'Premium')], max_length=128, verbose_name='Ценовая категория предпочитаемых брендов')),
                ('certificate', models.CharField(choices=[('none', 'нет'), ('torp', 'ТОРП'), ('st1', 'СТ1'), ('eac', 'EAC')], max_length=32, null=True, verbose_name='Сертификация')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Client')),
                ('lead_items', models.ManyToManyField(related_name='l_items', to='survey.Item', verbose_name='Лид')),
                ('order_items', models.ManyToManyField(related_name='o_items', to='survey.Item', verbose_name='Заявка')),
                ('query_items', models.ManyToManyField(related_name='q_items', to='survey.Item', verbose_name='Запрос')),
            ],
        ),
    ]
