# Generated by Django 2.1.3 on 2018-12-06 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name'], 'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактые лица'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['group', 'price_bracket', 'vendor2'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-added_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='query',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='subtype',
            field=models.CharField(blank=True, choices=[('force', 'Силовики'), ('gov_comp', 'Гос. компания'), ('gov_inst', 'Гос. учреждение'), ('gen_podr', 'Ген. подрядчик'), ('pr_comp', 'Частная компания'), ('smb', 'SMB')], max_length=64, verbose_name='Подтип'),
        ),
    ]
