# Generated by Django 2.0.2 on 2018-12-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='client',
            new_name='client_id',
        ),
    ]
