# Generated by Django 2.1.3 on 2018-12-07 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_auto_20181206_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='client',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
