# Generated by Django 2.0.2 on 2018-12-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20181227_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client_id',
        ),
    ]
