# Generated by Django 2.0.2 on 2018-12-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_contact_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=64, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=14, verbose_name='Телефон')),
                ('phone_number2', models.CharField(blank=True, max_length=14, verbose_name='Доп. телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Client')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактые лица',
                'ordering': ['last_name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='cl',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl_co', to='survey.Client'),
        ),
    ]
