# Generated by Django 2.0.2 on 2018-12-09 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20181207_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='form',
            field=models.CharField(choices=[('ООО', 'ooo'), ('ОАО', 'oao'), ('ПАО', 'pao'), ('ЗАО', 'zao'), ('АО', 'ao')], max_length=16, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='query',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Примечания к заказу'),
        ),
        migrations.AlterField(
            model_name='query',
            name='lead_items',
            field=models.ManyToManyField(null=True, related_name='l_items', to='survey.Item', verbose_name='Лид'),
        ),
        migrations.AlterField(
            model_name='query',
            name='order_items',
            field=models.ManyToManyField(null=True, related_name='o_items', to='survey.Item', verbose_name='Заявка'),
        ),
    ]
