# Generated by Django 2.0.2 on 2018-12-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20181227_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cl',
        ),
    ]
