# Generated by Django 2.0.2 on 2018-12-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20181210_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='crimea',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=6, verbose_name='Крым'),
        ),
        migrations.AlterField(
            model_name='client',
            name='governmental',
            field=models.CharField(choices=[('Государственная', 'Государственная'), ('Негосударственная', 'Негосударственная')], max_length=64, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='client',
            name='imp',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=6, verbose_name='Импортозамещение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sanctions',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=6, verbose_name='Санкции'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subtype',
            field=models.CharField(blank=True, choices=[('Силовики', 'Силовики'), ('Гос. компания', 'Гос. компания'), ('Гос. учреждение', 'Гос. учреждение'), ('Ген. подрядчик', 'Ген. подрядчик'), ('Частная компания', 'Частная компания'), ('SMB', 'SMB')], max_length=64, verbose_name='Подтип'),
        ),
    ]
