# Generated by Django 2.0.2 on 2018-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20181210_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='governmental',
            field=models.CharField(blank=True, choices=[('Государственная', 'Государственная'), ('Негосударственная', 'Негосударственная')], max_length=64, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subtype',
            field=models.CharField(blank=True, choices=[('Государственная', (('Силовики', 'Силовики'), ('Гос. компания', 'Гос. компания'), ('Гос. учреждение', 'Гос. учреждение'))), ('Негосударственная', (('Ген. подрядчик', 'Ген. подрядчик'), ('Частная компания', 'Частная компания'), ('SMB', 'SMB')))], max_length=64, verbose_name='Подтип'),
        ),
    ]
