# Generated by Django 2.0.2 on 2018-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20181229_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField(blank=True, verbose_name='Сервера')),
                ('shd', models.TextField(blank=True, verbose_name='СХД')),
                ('server_rack', models.TextField(blank=True, verbose_name='Сервер в форм факторе Rack')),
                ('server_tower', models.TextField(blank=True, verbose_name='Сервер в форм факторе Tower')),
                ('blade_server', models.TextField(blank=True, verbose_name='Блейд-сервер')),
                ('conv_inf', models.TextField(blank=True, verbose_name='Конвергентная инфраструктура')),
                ('shd_high', models.TextField(blank=True, verbose_name='СХД высокопроизводительного класса')),
                ('shd_common', models.TextField(blank=True, verbose_name='СХД общего назначения')),
                ('shd_begin', models.TextField(blank=True, verbose_name='СХД начального уровня')),
                ('shd_nas', models.TextField(blank=True, verbose_name='СХД система NAS')),
                ('shd_hybrid', models.TextField(blank=True, verbose_name='Гибридная СХД')),
                ('shd_reserv', models.TextField(blank=True, verbose_name='СХД для резервного копирования')),
                ('shd_vmware', models.TextField(blank=True, verbose_name='СХД для расширения VMware')),
                ('shd_video', models.TextField(blank=True, verbose_name='СХД для видеоконтента')),
                ('shd_program', models.TextField(blank=True, verbose_name='Программно-определяемая СХД')),
                ('new', models.TextField(blank=True, verbose_name='Покупка новых готовых систем')),
                ('upgrade', models.TextField(blank=True, verbose_name='Upgrade')),
                ('early_dell', models.TextField(blank=True, verbose_name='Ранее закупали Dell')),
                ('early_emc', models.TextField(blank=True, verbose_name='Ранее закупали EMC')),
                ('early_huawei', models.TextField(blank=True, verbose_name='Ранее закупали Huawei')),
                ('early_sugon', models.TextField(blank=True, verbose_name='Ранее закупали SUGON')),
                ('dell', models.TextField(blank=True, verbose_name='Ранее закупали Dell')),
                ('emc', models.TextField(blank=True, verbose_name='Ранее закупали EMC')),
                ('huawei', models.TextField(blank=True, verbose_name='Ранее закупали Huawei')),
                ('sugon', models.TextField(blank=True, verbose_name='Ранее закупали SUGON')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['pk'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
