# Generated by Django 2.0.2 on 2018-12-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20181210_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='subtype',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='governmental',
        ),
    ]
