# Generated by Django 2.0.2 on 2018-12-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20181229_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Текстовые блоки', 'verbose_name_plural': 'Текстовые блоки'},
        ),
    ]
