# Generated by Django 2.0.2 on 2018-12-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20181210_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, choices=[('Государственная', (('Силовики', 'Силовики'), ('Гос. компания', 'Гос. компания'), ('Гос. учреждение', 'Гос. учреждение'))), ('Негосударственная', (('Ген. подрядчик', 'Ген. подрядчик'), ('Частная компания', 'Частная компания'), ('SMB', 'SMB')))], max_length=64, verbose_name='Тип организации'),
        ),
    ]
