# Generated by Django 2.0.2 on 2018-12-11 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0009_auto_20181210_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=128, verbose_name='Тип организации')),
                ('sanctions', models.CharField(blank=True, max_length=128, verbose_name='Санкции')),
                ('crimea', models.CharField(blank=True, max_length=128, verbose_name='Крым')),
                ('imp', models.CharField(blank=True, max_length=128, verbose_name='Импортозамещение')),
                ('change', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientHist',
        ),
        migrations.RemoveField(
            model_name='client',
            name='changed_at',
        ),
        migrations.AddField(
            model_name='clientchange',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Client'),
        ),
        migrations.AddField(
            model_name='clientchange',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
