# Generated by Django 2.0.2 on 2019-01-04 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0009_auto_20181229_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.TextField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('father_name', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=14, verbose_name='Телефон')),
                ('phone_number2', models.CharField(blank=True, max_length=14, verbose_name='Доп. телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('position', models.CharField(blank=True, max_length=128, verbose_name='Должность')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Client')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
