# Generated by Django 2.0.2 on 2018-12-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20181211_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchange',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
