# Generated by Django 2.0.2 on 2019-01-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20190104_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('priority', models.IntegerField(verbose_name='Приоритет выдачи в списке')),
                ('price_cat', models.IntegerField(verbose_name='Ценовая категория')),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='fav_brands',
        ),
        migrations.AlterField(
            model_name='query',
            name='certificate',
            field=models.CharField(choices=[('ТОРП', 'ТОРП'), ('СТ1', 'СТ1'), ('EAC', 'EAC')], default='EAC', max_length=32, verbose_name='Сертификация'),
        ),
        migrations.AlterField(
            model_name='query',
            name='lead_items',
            field=models.ManyToManyField(blank=True, related_name='l_items', to='survey.Item', verbose_name='Лид'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_items',
            field=models.ManyToManyField(blank=True, related_name='q_items', to='survey.Item', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='query',
            name='upgrade',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=6, null=True, verbose_name='Апгрейд'),
        ),
        migrations.AddField(
            model_name='query',
            name='vendors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Vendor'),
        ),
    ]
