# Generated by Django 2.0.2 on 2018-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20181211_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
