# Generated by Django 2.0.2 on 2018-12-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_client_changed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='clientchange',
            name='crimea',
        ),
        migrations.RemoveField(
            model_name='clientchange',
            name='imp',
        ),
        migrations.RemoveField(
            model_name='clientchange',
            name='sanctions',
        ),
        migrations.RemoveField(
            model_name='clientchange',
            name='type',
        ),
    ]
