# Generated by Django 2.0.2 on 2019-01-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20190107_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='query',
            name='certificate',
        ),
        migrations.AddField(
            model_name='item',
            name='ST1',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], default='-', max_length=8, verbose_name='СТ1 ГОС образца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='eac',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], default='-', max_length=8, verbose_name='EAC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='torp',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], default='-', max_length=8, verbose_name='Сертификат ТОРП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='ST1',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=8, verbose_name='СТ1 ГОС образца'),
        ),
        migrations.AddField(
            model_name='query',
            name='eac',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=8, verbose_name='EAC'),
        ),
        migrations.AddField(
            model_name='query',
            name='torp',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=8, verbose_name='Сертификат ТОРП'),
        ),
        migrations.RemoveField(
            model_name='query',
            name='vendors',
        ),
        migrations.AddField(
            model_name='query',
            name='vendors',
            field=models.ManyToManyField(to='survey.Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет выдачи в списке(0-10)'),
        ),
    ]
