# Generated by Django 2.0.2 on 2018-12-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20181212_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchange',
            name='field',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
