# Generated by Django 2.0.2 on 2019-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20190107_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='ST1',
        ),
        migrations.RemoveField(
            model_name='query',
            name='eac',
        ),
        migrations.RemoveField(
            model_name='query',
            name='torp',
        ),
        migrations.AddField(
            model_name='query',
            name='certificate',
            field=models.ManyToManyField(to='survey.Certificate'),
        ),
    ]
