# Generated by Django 2.0.2 on 2018-12-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_clientchange_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientchange',
            name='field',
        ),
        migrations.AddField(
            model_name='clientchange',
            name='crimea',
            field=models.CharField(blank=True, max_length=6, verbose_name='Крым'),
        ),
        migrations.AddField(
            model_name='clientchange',
            name='imp',
            field=models.CharField(blank=True, max_length=6, verbose_name='Импортозамещение'),
        ),
        migrations.AddField(
            model_name='clientchange',
            name='sanctions',
            field=models.CharField(blank=True, max_length=6, verbose_name='Санкции'),
        ),
        migrations.AddField(
            model_name='clientchange',
            name='type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Тип организации'),
        ),
    ]
