# Generated by Django 2.0.2 on 2019-01-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20190107_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='price_bracket',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=64, verbose_name='Бюджет'),
        ),
    ]
