# Generated by Django 2.0.2 on 2018-12-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20181213_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientchange',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='clientchange',
            name='crimea',
            field=models.CharField(blank=True, max_length=6, verbose_name='Крым(old)'),
        ),
        migrations.AlterField(
            model_name='clientchange',
            name='imp',
            field=models.CharField(blank=True, max_length=6, verbose_name='Импортозамещение(old)'),
        ),
        migrations.AlterField(
            model_name='clientchange',
            name='sanctions',
            field=models.CharField(blank=True, max_length=6, verbose_name='Санкции(old)'),
        ),
        migrations.AlterField(
            model_name='clientchange',
            name='type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Тип организации(old)'),
        ),
    ]
