# Generated by Django 2.0.2 on 2019-01-09 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0015_auto_20190108_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='price_bracket',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='query',
            name='certificate',
            field=models.ManyToManyField(to='survey.Certificate', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='query',
            name='vendors',
            field=models.ManyToManyField(to='survey.Vendor', verbose_name='Ранее закупали'),
        ),
        migrations.AddField(
            model_name='querychange',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Query'),
        ),
    ]
