# Generated by Django 2.0.2 on 2019-01-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190109_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='form_factor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.RemoveField(
            model_name='query',
            name='form_factor',
        ),
        migrations.RemoveField(
            model_name='query',
            name='type',
        ),
        migrations.AlterField(
            model_name='item',
            name='SKU',
            field=models.CharField(max_length=64, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='item',
            name='SKU2',
            field=models.CharField(max_length=64, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(max_length=64, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(max_length=64, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model2',
            field=models.CharField(max_length=64, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_row',
            field=models.CharField(max_length=64, verbose_name='Модельный ряд'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_type',
            field=models.CharField(choices=[('Сервер', (('Форм-фактор Rack', 'Форм-фактор Rack'), ('Форм-фактор Tower', 'Форм-фактор Tower'), ('Блейд-сервер', 'Блейд-сервер'))), ('СХД', (('СХД начального уровня', 'СХД начального уровня'), ('СХД общего назначения', 'СХД общего назначения'), ('Гибридная СХД', 'Гибридная СХД'), ('СХД для резервного копирования', 'СХД для резервного копирования'), ('СХД высокопроизводительного класса', 'СХД высокопроизводительного класса'), ('СХД система NAS', 'СХД система NAS'), ('СХД для расширения VMware', 'СХД для расширения VMware'), ('Программно-определяемая СХД', 'Программно-определяемая СХД'), ('СХД для видеоконтента', 'СХД для видеоконтента')))], max_length=64, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor1',
            field=models.CharField(max_length=64, verbose_name='Вендор'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor2',
            field=models.CharField(max_length=64, verbose_name='Вендор'),
        ),
        migrations.AlterField(
            model_name='query',
            name='product_type',
            field=models.CharField(choices=[('Сервер', (('Форм-фактор Rack', 'Форм-фактор Rack'), ('Форм-фактор Tower', 'Форм-фактор Tower'), ('Блейд-сервер', 'Блейд-сервер'))), ('СХД', (('СХД начального уровня', 'СХД начального уровня'), ('СХД общего назначения', 'СХД общего назначения'), ('Гибридная СХД', 'Гибридная СХД'), ('СХД для резервного копирования', 'СХД для резервного копирования'), ('СХД высокопроизводительного класса', 'СХД высокопроизводительного класса'), ('СХД система NAS', 'СХД система NAS'), ('СХД для расширения VMware', 'СХД для расширения VMware'), ('Программно-определяемая СХД', 'Программно-определяемая СХД'), ('СХД для видеоконтента', 'СХД для видеоконтента')))], max_length=64, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='query',
            name='vendors',
            field=models.ManyToManyField(to='survey.Vendor', verbose_name='Предпочтения'),
        ),
    ]
