# Generated by Django 2.0.2 on 2018-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20181219_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imp',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('?', '?')], max_length=6, verbose_name='Импортозамещение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='crimea',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('?', '?')], max_length=6, verbose_name='Крым'),
        ),
        migrations.AlterField(
            model_name='client',
            name='imp',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('?', '?')], max_length=6, verbose_name='Импортозамещение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sanctions',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('?', '?')], max_length=6, verbose_name='Санкции'),
        ),
        migrations.AlterField(
            model_name='item',
            name='crimea',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('?', '?')], max_length=8, verbose_name='Крым'),
        ),
        migrations.AlterField(
            model_name='item',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('Форм-фактор Rack', 'Форм-фактор Rack'), ('Форм-фактор Tower', 'Форм-фактор Tower'), ('Блейд-сервер', 'Блейд-сервер')], max_length=64, null=True, verbose_name='Форм-фактор сервера'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sanctions',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('?', '?')], max_length=8, verbose_name='Санкции'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('СХД начального уровня', 'СХД начального уровня'), ('СХД общего назначения', 'СХД общего назначения'), ('Гибридная СХД', 'Гибридная СХД'), ('СХД для резервного копирования', 'СХД для резервного копирования'), ('СХД высокопроизводительного класса', 'СХД высокопроизводительного класса'), ('СХД система NAS', 'СХД система NAS'), ('СХД для расширения VMware', 'СХД для расширения VMware'), ('Программно-определяемая СХД', 'Программно-определяемая СХД'), ('СХД для видеоконтента', 'СХД для видеоконтента')], max_length=64, null=True, verbose_name='Тип СХД'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upgrade',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('?', '?')], max_length=6, null=True, verbose_name='Апгрейд'),
        ),
    ]
